#定义服务应用名称
spring:
  application:
    name: webchat
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  swagger:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:logback-spring.xml


